//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WomenFitnessClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Coaches = new HashSet<Coach>();
        }
    
        public string Code { get; set; }
        public string Days { get; set; }
        public string Time { get; set; }
        public string CoachName { get; set; }
    
        public virtual ICollection<Coach> Coaches { get; set; }
    }
}
